# seed.py
from app import create_app
from app.extensions import db
from app.models import Product

PRODUCTS = [
    ("Aceite girasol", "l", "Aceites"),
    ("Aceite virgen extra", "l", "Aceites"),
    ("Ajetes", "kg", "Verduras"),
    ("Ajo pelado", "kg", "Verduras"),
    ("Alcachofa", "uds", "Verduras"),
    ("Ali-oli", "bote", "Condimentos"),
    ("Almeja", "kg", "Conservas"),
    ("Amoniaco", "botella", "Limpieza"),
    ("Anchoa marinera", "lata", "Conservas"),
    ("Anchoa santoña", "lata", "Conservas"),
    ("Arroz", "kg", "Despensa"),
    ("Atún en aceite", "lata", "Conservas"),
    ("Bacon", "kg", "Carnes"),
    ("Berenjena", "kg", "Verduras"),
    ("Bogavante", "uds", "Pescados"),
    ("Burrante (200g)", "uds", "Congelados"),
    ("Cachopo", "uds", "Congelados"),
    ("Calabaza dados", "kg", "Verduras"),
    ("Calamar", "kg", "Pescados"),
    ("Caldo de carne", "litro", "Conservas"),
    ("Caldo de pescado", "litro", "Conservas"),
    ("Caldo pollo", "litro", "Conservas"),
    ("Carne arroz", "kg", "Carnes"),
    ("Cazón (200g)", "uds", "Congelados"),
    ("Cebolla morada", "kg", "Verduras"),
    ("Chanquete", "kg", "Pescados"),
    ("Chimi churri", "bote", "Condimentos"),
    ("Chopitos (500g)", "uds", "Congelados"),
    ("Cigalitas", "kg", "Pescados"),
    ("Codillo", "kg", "Carnes"),
    ("Crema calabaza", "lata", "Conservas"),
    ("Croquetas boletus", "uds", "Congelados"),
    ("Croquetas carrillera", "uds", "Congelados"),
    ("Croquetas gambas", "uds", "Congelados"),
    ("Croquetas de jamón", "uds", "Congelados"),
    ("Cucuruchos", "uds", "Panadería"),
    ("Dulce de leche", "tarro", "Dulces"),
    ("Ensalada de col", "kg", "Preparados"),
    ("Ensaladilla (2.5k)", "uds", "Preparados"),
    ("Entrecot (400g)", "uds", "Carnes"),
    ("Escalope de cerdo", "uds", "Carnes"),
    ("Fideuá", "kg", "Despensa"),
    ("Galleta entera", "uds", "Panadería"),
    ("Galleta molida", "kg", "Panadería"),
    ("Gamba roja", "kg", "Pescados"),
    ("Gambas (1000g)", "kg", "Pescados"),
    ("Gambón nems", "uds", "Congelados"),
    ("Gambusi (200g)", "uds", "Congelados"),
    ("Gindillas", "kg", "Condimentos"),
    ("Guacamole", "bote", "Preparados"),
    ("Harina fritura", "kg", "Despensa"),
    ("Huevos", "docena", "Lácteos"),
    ("Ketchup", "botella", "Condimentos"),
    ("Leche", "l", "Lácteos"),
    ("Lechuga", "uds", "Verduras"),
    ("Limón", "kg", "Frutas"),
    ("Mayonesa", "botella", "Condimentos"),
    ("Mayonesa cítrica", "botella", "Condimentos"),
    ("Mayonesa trufa", "botella", "Condimentos"),
    ("Melón", "uds", "Frutas"),
    ("Melón cantaloup", "uds", "Frutas"),
    ("Merluza", "kg", "Pescados"),
    ("Miel de caña", "tarro", "Condimentos"),
    ("Miel y mostaza", "bote", "Condimentos"),
    ("Muslo de pollo", "kg", "Carnes"),
    ("Naranja", "kg", "Frutas"),
    ("Nata", "l", "Lácteos"),
    ("Padrón", "kg", "Verduras"),
    ("Pan bocadillo", "uds", "Panadería"),
    ("Pan brioché trenzado", "uds", "Panadería"),
    ("Pan chapatón", "uds", "Panadería"),
    ("Pan hogaza", "uds", "Panadería"),
    ("Panko", "kg", "Despensa"),
    ("Papel de arroz (nems)", "uds", "Despensa"),
    ("Pasta wok", "kg", "Despensa"),
    ("Patata pochada (250g)", "uds", "Preparados"),
    ("Patatas bravas (250g)", "uds", "Preparados"),
    ("Patatas fritas", "kg", "Despensa"),
    ("Pesto", "bote", "Condimentos"),
    ("Picatostes", "kg", "Despensa"),
    ("Pimiento de piquillo", "kg", "Verduras"),
    ("Pimiento mix", "kg", "Verduras"),
    ("Piña", "uds", "Frutas"),
    ("Pisto (1000g)", "uds", "Preparados"),
    ("Pollo cesar", "uds", "Preparados"),
    ("Pulpo", "kg", "Pescados"),
    ("Queso cheddar", "kg", "Lácteos"),
    ("Queso parmesano", "kg", "Lácteos"),
    ("Rape tacos", "kg", "Pescados"),
    ("Regaña ensaladilla", "uds", "Panadería"),
    ("Rúcula", "kg", "Verduras"),
    ("Sal fina", "kg", "Condimentos"),
    ("Sal gruesa", "kg", "Condimentos"),
    ("Sal maldón", "uds", "Condimentos"),
    ("Sal maldón negra", "uds", "Condimentos"),
    ("Salmón (250g)", "uds", "Pescados"),
    ("Salmón ahumado", "kg", "Pescados"),
    ("Salmorreta", "bote", "Condimentos"),
    ("Salsa brava", "bote", "Condimentos"),
    ("Salsa bilbaina", "bote", "Condimentos"),
    ("Salsa cesar", "bote", "Condimentos"),
    ("Salsa verde", "bote", "Condimentos"),
    ("Sandía", "uds", "Frutas"),
    ("Sepia", "kg", "Pescados"),
    ("Setas", "kg", "Verduras"),
    ("Sirope de mango", "botella", "Condimentos"),
    ("Sirope de frambuesa", "botella", "Condimentos"),
    ("Soja", "botella", "Condimentos"),
    ("Sweet chili", "botella", "Condimentos"),
    ("Tarta de chocolate", "uds", "Postres"),
    ("Tarta de queso", "uds", "Postres"),
    ("Tarta de limón", "uds", "Postres"),
    ("Tarta manzana", "uds", "Postres"),
    ("Tinta negra", "botella", "Condimentos"),
    ("Tomate caramelizado", "bote", "Conservas"),
    ("Tomate frito", "bote", "Conservas"),
    ("Tomate rosa", "kg", "Verduras"),
    ("Torrija", "uds", "Postres"),
    ("Tortilla camaron", "uds", "Preparados"),
    ("Verdura wok", "kg", "Verduras"),
    ("Zamburiña", "kg", "Pescados"),
    ("Zanahoria", "kg", "Verduras"),
    # limpieza y menaje
    ("Abrillantador maq lav", "botella", "Limpieza"),
    ("Bayetas", "uds", "Limpieza"),
    ("Delantales friege", "uds", "Limpieza"),
    ("Estropajos", "uds", "Limpieza"),
    ("Escoba", "uds", "Limpieza"),
    ("Fregasuelos", "litro", "Limpieza"),
    ("Fregona", "uds", "Limpieza"),
    ("Guantes friegue", "par", "Limpieza"),
    ("Guantes L", "par", "Limpieza"),
    ("Guantes M", "par", "Limpieza"),
    ("Guantes S", "par", "Limpieza"),
    ("Guantes XL", "par", "Limpieza"),
    ("Jabón manual", "litro", "Limpieza"),
    ("Jabón máquina lav.", "litro", "Limpieza"),
    ("Lejía", "litro", "Limpieza"),
    ("Limpia superficies", "litro", "Limpieza"),
    ("Papel mecha", "rollo", "Limpieza"),
    ("Papel anti grasa", "hojas", "Limpieza"),
    ("Papel film", "rollo", "Limpieza"),
    ("Quita grasas", "litro", "Limpieza"),
]

def run():
    app = create_app()
    with app.app_context():
        # Crear tablas si no existen
        db.create_all()
        # insertar si no existe
        for nombre, unidad, categoria in PRODUCTS:
            exists = Product.query.filter_by(nombre=nombre).first()
            if not exists:
                p = Product(nombre=nombre, unidad=unidad, cantidad=0, categoria=categoria)
                db.session.add(p)
        db.session.commit()
        print("Seed completo: productos añadidos (si no existían).")

if __name__ == "__main__":
    run()