"""empty message

Revision ID: 6a5c7b6292e2
Revises: 0cf2c8108895
Create Date: 2026-02-10 17:54:35.633914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5c7b6292e2'
down_revision = '0cf2c8108895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('cif', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('notas')
        batch_op.drop_column('cif')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
