"""Crear tabla movimientos

Revision ID: 997e72159a25
Revises: 74aca0426af0
Create Date: 2025-12-02 23:37:29.227542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997e72159a25'
down_revision = '74aca0426af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos')
    # ### end Alembic commands ###
